apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tester
    aadpodidbinding: tester
  name: tester
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: tester
        aadpodidbinding: tester
    spec:
      containers:
      - name: tester
        image: "flanagan89/msi-tester:v5"
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP