apiVersion: v1
kind: Service
metadata:
  name: tester-service
  labels:
    app: tester-service
spec:
  type: LoadBalancer
  ports:
  - port: 88
    targetPort: 80
    protocol: TCP
  selector:
    app: tester